apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-kube-apiserver-to-quic-tunnel
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: kubernetes
      role: apiserver
  egress:
  - {}
  policyTypes:
  - Egress
